# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgb(40C1F2)

general {
    col.active_border = $activeBorderColor
}

group {
    col.border_active = $activeBorderColor
}
animations {
    enabled = true

    bezier = smoothFast, 0.25, 1, 0.5, 1


    animation = workspaces, 1, 2, smoothFast, slide
    
    animation = windows, 1, 2, smoothFast
}